#!/usr/bin/env bash

PROJECT_ROOT=${PROJECT_ROOT:-$(git rev-parse --show-toplevel)}

red=`tput setab 1 2>/dev/null || true`
yellow=`tput setab 3 2>/dev/null || true`
green=`tput setab 2 2>/dev/null || true`
blue=`tput setab 4 2>/dev/null || true`
reset=`tput sgr0 2>/dev/null || true`
bold=`tput bold 2>/dev/null || true`

die ( ) {
    echo
    echo "${bold}${red} $* ${reset}"
    echo
    exit 1
}

ensure ( ) {
    command -v $1 >/dev/null 2>&1 || die "ERROR: '$1' could be found in your PATH. Please install $1. $2"
}

info ( ) {
    echo "${bold}${blue} $* ${reset}"
}

success ( ) {
    echo "${bold}${green} $* ${reset}"
}

rm -rf out || true
mkdir -p out/kotlinannotation

info "Starting compiling kotlinannotation"
kotlin-home/libexec/bin/kotlinc \
$PROJECT_ROOT/kotlinannotation/KotlinAnnotation.kt \
-d $PROJECT_ROOT/out/kotlinannotation \
-classpath \
$PROJECT_ROOT/kotlin-home/libexec/lib/kotlin-stdlib.jar \
-module-name annotation-lib \
-jvm-target 1.8 \
-no-stdlib \
-no-reflect \
-Werror \
&& (cd out/kotlinannotation && \
    zip -r kotlinannotation META-INF kotlinannotation > /dev/null 2>&1 && \
    mv kotlinannotation.zip kotlinannotation.jar && \
    rm -rf META-INF kotlinannotation/* && \
    rmdir kotlinannotation) \
&& success "kotlinannotation lib compilation COMPLETE." || die "kotlinannotation lib compilation FAILED."


mkdir -p out/kotlinap/stubs
mkdir -p out/kotlinap/classes
mkdir -p out/kotlinap/incremental
mkdir -p out/kotlinap/sources

EMPTY_MAP="rO0ABXcEAAAAAA==" # encoded empty map

info "Starting compiling kotlinap lib"
kotlin-home/libexec/bin/kotlinc \
$PROJECT_ROOT/kotlinap/AnnotationProcessorKotlin.kt \
-d $PROJECT_ROOT/out/kotlinap \
-classpath \
$PROJECT_ROOT/kotlin-home/libexec/lib/kotlin-stdlib.jar:\
$PROJECT_ROOT/out/kotlinannotation/kotlinannotation.jar:\
$PROJECT_ROOT/libs/auto-common.jar:\
$PROJECT_ROOT/libs/auto-service.jar:\
$PROJECT_ROOT/libs/guava.jar:\
$PROJECT_ROOT/libs/kotlinpoet.jar \
-module-name kotlinap-lib \
-no-stdlib \
-no-reflect \
-jvm-target 1.8 \
-Werror \
-Xplugin=$PROJECT_ROOT/kotlin-home/libexec/lib/kotlin-annotation-processing-gradle.jar \
-P plugin:org.jetbrains.kotlin.kapt3:aptMode=compile \
-P plugin:org.jetbrains.kotlin.kapt3:apclasspath=$PROJECT_ROOT/libs/kotlin-stdlib.jar \
-P plugin:org.jetbrains.kotlin.kapt3:apclasspath=$PROJECT_ROOT/libs/kotlin-reflect.jar \
-P plugin:org.jetbrains.kotlin.kapt3:apclasspath=$PROJECT_ROOT/libs/kotlin-compiler-embeddable.jar \
-P plugin:org.jetbrains.kotlin.kapt3:apclasspath=$PROJECT_ROOT/libs/trove4j.jar \
-P plugin:org.jetbrains.kotlin.kapt3:apclasspath=$PROJECT_ROOT/libs/auto-common.jar \
-P plugin:org.jetbrains.kotlin.kapt3:apclasspath=$PROJECT_ROOT/libs/auto-service.jar \
-P plugin:org.jetbrains.kotlin.kapt3:apclasspath=$PROJECT_ROOT/libs/guava.jar \
-P plugin:org.jetbrains.kotlin.kapt3:sources=$PROJECT_ROOT/out/kotlinap/tmp/classes/sources \
-P plugin:org.jetbrains.kotlin.kapt3:classes=$PROJECT_ROOT/out/kotlinap/tmp/classes/classes \
-P plugin:org.jetbrains.kotlin.kapt3:incrementalData=$PROJECT_ROOT/out/kotlinap/tmp/classes/incremental \
-P plugin:org.jetbrains.kotlin.kapt3:stubs=$PROJECT_ROOT/out/kotlinap/tmp/stubs \
-P plugin:org.jetbrains.kotlin.kapt3:apoptions=$EMPTY_MAP \
-P plugin:org.jetbrains.kotlin.kapt3:javacArguments=$EMPTY_MAP \
-P plugin:org.jetbrains.kotlin.kapt3:useLightAnalysis=true \
-P plugin:org.jetbrains.kotlin.kapt3:correctErrorTypes=false \
-P plugin:org.jetbrains.kotlin.kapt3:verbose=true \
&& (cd out/kotlinap && \
    zip -r kotlinap META-INF kotlinap classes sources > /dev/null 2>&1 && \
    mv kotlinap.zip kotlinap.jar && \
    rm -rf META-INF classes stubs incremental sources kotlinap/* && \
    rmdir kotlinap) \
&& success "kotlinap lib compilation COMPLETE." || die "kotlinap lib compilation FAILED."

